= Iron Caterpillar API Guide
JVM Guy;
:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs

[[overview]]
= Overview

[[service-overview]]
== Service Overview

Iron Caterpillar, aka IC, is an immutable blob storage service.  The bytes uploaded to the system are uninterpreted and stored in their
raw format.  Meta-data that is sent during the upload is also stored along side the bytes.  Once a blob is uploaded, there is no way to
remove it from the system.  Modifications, however, to the meta-data are allowed.

[[overview-http-verbs]]
== HTTP verbs

The Application tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to update the meta-data of an existing resource

| `PATCH`
| Not currently supported

| `DELETE`
| Not currently supported

| `HEAD`
| Used to obtain meta-data about the resource but not download the blob itself

| `OPTIONS`
| Not currently supported
|===

[[overview-http-status-codes]]
== HTTP status codes

The Application tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully.

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header.

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information.

| `404 Not Found`
| The requested resource did not exist. The response body will include an error providing further information.

| `411 Length Required`
| The request is missing the required Content- Length header. The response body will include an error providing further information.

| `412 Precondition Failed`
| The request is missing a required custom header. The response body will include an error providing further information.

| `413 Request Entity Too Large`
| The uploaded entity is too large for the service to handle. The response body will include an error providing further information.
|===

[[overview-http-headers]]
== Required HTTP headers

A small number of HTTP headers are required to be in all requests.

|===
| Header | Usage

| `X-Correlation-Id`
| The service is part of a large network of cooperating services and publishes its log messages to a centralized server.  To facilitate the tracing of events and messages between systems, the application requires that a correlation id be provided with each request. If the client is the initiator of an action, then a new id should be generated.  If the client, however, is reacting to an outside event or message, the client should propagate the correlation id it was handed.
|===

== Cache HTTP headers

The system is HTTP cache-friendly and most replies will contain headers that will assist the client-side cache.

|===
| Header | Usage

| `ETag`
| When the asset is initially `POST`ed into the system the `ETag` header will be filled in with an opaque value that
the client can use to conditionlly `GET` the asset and save some network bandwidth.  Since the uploaded assets are immutable, the `ETag` will
never change.
|===

[[overview-errors]]
== Errors

Most operations return a hypermedia control. Whenever an error response (status code >= 400) is returned,
the control will contain information that describes the problem. The control will populate the following fields in a failure scenario:

|===
| Field | Description

| `http-code`
| The HTTP status code being returned, e.g. 413.  Useful for clients that have difficulty accessing HTTP headers.

| `code`
| An integer code uniquely identifying the error message being returned. Helpful when troubleshooting failures.

| `message`
| A short message describing the problem using terms suitable for end users.

| `developer-message`
| A more detailed message describing the problem using terms suitable for developers.
|===

For example, a request that attempts to fetch a non-existent asset will produce a
`400 Bad Request` response:

include::{generated}/failure-scenario/curl-request.adoc[]
include::{generated}/failure-scenario/http-request.adoc[]
include::{generated}/failure-scenario/http-response.adoc[]

[[overview-hypermedia]]
== Hypermedia

The application uses a simple hypermedia control that includes links to other resources that the client
can use to navigate around the service. Links can be found beneath the `_links` key. The control is an
extension of http://stateless.co/hal_specification.html[HAL media type].

IMPORTANT:  Users of the API should not create URIs themselves, instead they should use
the above-described links to navigate from resource to resource.  Failure to observe this rule will undoubtedly
result in errors as service location and URIs change.

[[overview-miscellaneous]]
== Miscellaneous

The application does not currently require any form of authentication, expecting that the service will not be
exposed directly to the public internet.  The application does not currently rate limit requests, expecting that
API users will be prudent in their use of the service.

[[resources]]
= Resources

[[resources-index]]
== Binary Asset

A Binary Asset is a collection of bytes that are permanently stored on the server.
During the upload process, additional meta-data can be added to the asset for later
retrieval.

[[api-discovery]]
=== API discovery

A `GET` request will return a collection of links to the currently supported resources.
Interpreting those resources will allow the API user to navigate the API without having
to hard code well-known URIs.

IMPORTANT: The API and its URIs are likely to change over time so it is important the caller
always begin a session with API discovery to obtain the currently supported URIs.

==== Example Conversation

include::{generated}/api-discovery/curl-request.adoc[]
include::{generated}/api-discovery/http-request.adoc[]
include::{generated}/api-discovery/http-response.adoc[]

[[asset-upload]]
=== Uploading the asset

A `POST` request is used to upload the asset.  The `Content-Type` header is used to communicate
both the asset's actual type and additional meta-data.  The application adheres to the https://tools.ietf.org/html/rfc2045[RFC 2045]
standard and makes use of MIME type parameters to communicate additional information.  Example usages include
specifying an image's height and width or an audio file's sample rate.  The response will contain the hypermedia control
describing the successful operation as well as other resources that can be accessed. Since IC is an immutable store, in the case of a
partial failure it is safe and expected to retry the `POST`.  If the asset already exists in the system, no conflict will flagged.

|===
| Notable Header | Usage
| `Accept`
| This header is used to indicate the format of the response.  It is always the MIME type of the hypermedia control.
| `Content-Length`
| This header is used to indicate the size, in bytes, of the asset being uploaded.
| `Content-MD5`
| This header is used to ensure the asset being uploaded arrives uncorrupted.  Fill the header with the Base64 encoding of the MD5 digest of the asset.
| `Content-Type`
| This header is used to indicate the exact format of the asset being uploaded, including version.
| `X-Uploaded-By`
| Identifies the application communicating with the service and is used primarily for logging and reporting purposes.  The contents are never
interpreted but be should unique within the enterprise.  Examples include 'my cool application', 'mobile application v1.0.1'.
|===

==== Example Conversation

include::{generated}/asset-storage/curl-request.adoc[]
include::{generated}/asset-storage/http-request.adoc[]
include::{generated}/asset-storage/http-response.adoc[]

[[asset-download]]
=== Downloading the asset

A `GET` request is used to fetch the asset.

IMPORTANT: The `Accept` header must be configured to accept both the MIME type of the asset as
well as the MIME type of the hypermedia control.  In the event of a failure, the control will be
returned instead of the asset.

==== Example Conversation

include::{generated}/asset-download/curl-request.adoc[]
include::{generated}/asset-download/http-request.adoc[]
include::{generated}/asset-download/http-response.adoc[]

[[current-limitations]]
=== Current Limitations

The service currently does support the ability to obtain the asset's meta-data other than what is returned as part of
the original upload.  It should be possible to support a combination of `GET` and the `Accept` header to support obtaining
just the meta-data if enough API users request the feature.
